### ISSUE TITLE
practia4

### ISSUE THREAD

**Issue by jdnarvaez0** [Miguel-Alejandro-Castillo/LenguajeAssemblyUNLP#1]
Hola, como estas?
Veo que estas viendo la materia de Arqui, una consulta, estas haciendo la practica 4. Me esta costando resolverla.

**Comment by Miguel-Alejandro-Castillo** [comment]
Buenas noches Juan, bien y vos?
 Aun no empece la practica 4 pero te puedo compartir un link con las practicas  resueltas de arquitectura 2012
https://ydray.com/get/l/ri16201711301403/WJ1h7mDlxQo
Nota: en 7 dias se elimina ese archivo subido en ydray
Ojala te sirva
Saludos, 
Miguel

**Comment by jdnarvaez0** [comment]
Muchas gracias Miguel. Saludos
